version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    links:
      - wordpressdb:mysql
    ports:
      - 8081:80
    environment:
       WORDPRESS_DB_HOST: wordpressdb:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

  wordpressdb:
    image: mysql:5.7
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
